---

- name: Merge cluster and group config
  set_fact:
    temp_group_rke2_config: >-
      {{ cluster_rke2_config | default({}) |
         combine(group_rke2_config | default({})) }}

- name: Merge host config
  set_fact:
    rke2_config: >-
      {{ temp_group_rke2_config | default({}) |
         combine(host_rke2_config | default({})) }}

- name: Set API endpoint
  set_fact:
    rke2_config: >-
      {{
        rke2_config |
        combine({
          'server': 'https://' + (haproxy_ip if haproxy_enabled else ansible_host) + ':9345'
        })
      }}


- name: Add HAProxy to TLS SAN
  set_fact:
    rke2_config: >-
      {{
        rke2_config |
        combine({
          'tls_san': (rke2_config.get('tls_san', []) + [haproxy_ip]) | unique
        })
      }}
  when: haproxy_enabled


- name: Write RKE2 config.yaml
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: "0600"
  notify: Restart {{ service_name }}

##